// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0FAeFnmm5uHYf7x5-4-evdL74Spsu6Xw',
    appId: '1:506163907390:web:6d4de0a056bfae90f0ba6f',
    messagingSenderId: '506163907390',
    projectId: 'city-cab-booking',
    authDomain: 'city-cab-booking.firebaseapp.com',
    storageBucket: 'city-cab-booking.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn8WOV5-9p-0wLSlO3C5RmNPfudb56ddQ',
    appId: '1:506163907390:android:a600fe5da70f8c56f0ba6f',
    messagingSenderId: '506163907390',
    projectId: 'city-cab-booking',
    storageBucket: 'city-cab-booking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_k1A9bmuRZdyqTN3Y5lOLeIzdmF-WDEg',
    appId: '1:506163907390:ios:000b8b8e459afabef0ba6f',
    messagingSenderId: '506163907390',
    projectId: 'city-cab-booking',
    storageBucket: 'city-cab-booking.firebasestorage.app',
    iosBundleId: 'com.example.fooddeliveryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0FAeFnmm5uHYf7x5-4-evdL74Spsu6Xw',
    appId: '1:506163907390:web:17f937ef04fd4f5bf0ba6f',
    messagingSenderId: '506163907390',
    projectId: 'city-cab-booking',
    authDomain: 'city-cab-booking.firebaseapp.com',
    storageBucket: 'city-cab-booking.firebasestorage.app',
  );
}